### ISSUE TITLE
Broken Psychic Harmonizer mood

### ISSUE THREAD

**Issue by JulianSkies** [Tachyonite/Pawnmorpher#281]
**Describe the bug**
Upon morphing a pawn, if they were under a Psychic Harmonizer mood effect, the Needs tab becomes blank and the Psychic Harmonizer moodlet loses it's origin pawn.

**To Reproduce**
1. Select a pawn to be transformed
2. Send them to the mutation chamber, ensure a pawn with a Psychic Harmonizer is in range as they enter
3. Start mutation
4. Upon mutation finishing, check Needs tab

**Error Log**
I noticed the error because RimHUD complained, so here's the log it generated: https://pastebin.com/XX1xTBZy
Also the expected hugslog: https://gist.github.com/HugsLibRecordKeeper/6026bb2f58bf562c9e15b055ca9d0930

**Expected behavior**
Expected the moodlet to be unaffected

**Additional context**
Greater details:
Pawn used was a Cutebold, from the same-named mod
Pawn already had a bunch of megasloth mutations
The animal the pawn was transformed into was a Harbinger Dragon from Dragon's Descent - Void Dwellers
I noticed the error through RimHUD complaining, it was fixed by removing the Psychic Harmonizer mood using Character Editor. When checking Character Creator I noticed that the Psychic Harmonizer moodlet had a string name instead of the name of the pawn that originates it, and when I removed it various other thoughts that should have been in the list and weren't appeared.
Also credit to Abraxas for helping me figure out this specific mood was the problem.

**Comment by codeninja** [comment]
I also had this issue as well, I had to remove all references to Psychic Harmonizer from my save game.

**Comment by FxWolfxe** [comment]
should be fixed in the latest version

**Comment by codeninja** [comment]
Excellent! Thank you.

**Comment by codeninja** [comment]
Did this ever get updated in the steam library? I'm still seeing this issue on a new playthrough with fresh mod download.
