### ISSUE TITLE
Pawns Refuse to Eat

### ISSUE THREAD

**Issue by KonaNeedsHelp** [Tachyonite/Pawnmorpher#288]
Pawns Continually fail to eat food, eventually starving themselves into mental breaks followed by death. If left alone, they completely ignore any food on the map or in stockpile zones. If forced, they will pick up a piece of food, begin eating it, then put it back down when the bar fills.

All mods are up to date, and I've attempted the fix given for this issue in the past to no effect

Version is:
RimWorld 1.2.2753 rev705

Mod order is:
Harmony
Core
Royalty
HugsLib
Humanoid Alien Races 2.0
EdB Prepare Carfully
Pawnmorpher

Got this message from the Player.log

Hotspot analysis

----------------------------------------

1x ExecuteToExecuteWhenFinished() -> 0.0142 ms (total (w/children): 0.0154 ms)

1x Verse.Sound.Sustainer -> Void <.ctor>b__15_0() -> 0.0012 ms (total (w/children): 0.0012 ms)

Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.MissingFieldException: Field 'AlienRace.AteThought.thought' not found.
  at Pawnmorph.PawnmorphPatches.ThoughtsFromIngestingPostfix (Verse.Pawn ingester, Verse.Thing foodSource, System.Collections.Generic.List`1[RimWorld.ThoughtDef]& __result) [0x00001] in <a21eea8abe644d3eba223dadb787361b>:0 
  at (wrapper dynamic-method) RimWorld.FoodUtility.RimWorld.FoodUtility.ThoughtsFromIngesting_Patch2(Verse.Pawn,Verse.Thing,Verse.ThingDef)
  at RimWorld.FoodUtility.FoodOptimality (Verse.Pawn eater, Verse.Thing foodSource, Verse.ThingDef foodDef, System.Single dist, System.Boolean takingToInventory) [0x000a0] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at RimWorld.FoodUtility.SpawnedFoodSearchInnerScan (Verse.Pawn eater, Verse.IntVec3 root, System.Collections.Generic.List`1[T] searchSet, Verse.AI.PathEndMode peMode, Verse.TraverseParms traverseParams, System.Single maxDistance, System.Predicate`1[T] validator) [0x00066] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at (wrapper dynamic-method) RimWorld.FoodUtility.RimWorld.FoodUtility.BestFoodSourceOnMap_Patch1(Verse.Pawn,Verse.Pawn,bool,Verse.ThingDef&,RimWorld.FoodPreferability,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,RimWorld.FoodPreferability)
  at RimWorld.FoodUtility.TryFindBestFoodSourceFor (Verse.Pawn getter, Verse.Pawn eater, System.Boolean desperate, Verse.Thing& foodSource, Verse.ThingDef& foodDef, System.Boolean canRefillDispenser, System.Boolean canUseInventory, System.Boolean allowForbidden, System.Boolean allowCorpse, System.Boolean allowSociallyImproper, System.Boolean allowHarvest, System.Boolean forceScanWholeMap, System.Boolean ignoreReservations, RimWorld.FoodPreferability minPrefOverride) [0x000a5] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at RimWorld.JobGiver_GetFood.TryGiveJob (Verse.Pawn pawn) [0x0008d] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at Verse.AI.ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00000] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x000fc] in <6326ac03f61f45efb3178f3bfd084139>:0 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.MissingFieldException: Field 'AlienRace.AteThought.thought' not found.
  at Pawnmorph.PawnmorphPatches.ThoughtsFromIngestingPostfix (Verse.Pawn ingester, Verse.Thing foodSource, System.Collections.Generic.List`1[RimWorld.ThoughtDef]& __result) [0x00001] in <a21eea8abe644d3eba223dadb787361b>:0 
  at (wrapper dynamic-method) RimWorld.FoodUtility.RimWorld.FoodUtility.ThoughtsFromIngesting_Patch2(Verse.Pawn,Verse.Thing,Verse.ThingDef)
  at RimWorld.FoodUtility.FoodOptimality (Verse.Pawn eater, Verse.Thing foodSource, Verse.ThingDef foodDef, System.Single dist, System.Boolean takingToInventory) [0x000a0] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at RimWorld.FoodUtility.SpawnedFoodSearchInnerScan (Verse.Pawn eater, Verse.IntVec3 root, System.Collections.Generic.List`1[T] searchSet, Verse.AI.PathEndMode peMode, Verse.TraverseParms traverseParams, System.Single maxDistance, System.Predicate`1[T] validator) [0x00066] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at (wrapper dynamic-method) RimWorld.FoodUtility.RimWorld.FoodUtility.BestFoodSourceOnMap_Patch1(Verse.Pawn,Verse.Pawn,bool,Verse.ThingDef&,RimWorld.FoodPreferability,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,RimWorld.FoodPreferability)
  at RimWorld.FoodUtility.TryFindBestFoodSourceFor (Verse.Pawn getter, Verse.Pawn eater, System.Boolean desperate, Verse.Thing& foodSource, Verse.ThingDef& foodDef, System.Boolean canRefillDispenser, System.Boolean canUseInventory, System.Boolean allowForbidden, System.Boolean allowCorpse, System.Boolean allowSociallyImproper, System.Boolean allowHarvest, System.Boolean forceScanWholeMap, System.Boolean ignoreReservations, RimWorld.FoodPreferability minPrefOverride) [0x000a5] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at RimWorld.JobGiver_GetFood.TryGiveJob (Verse.Pawn pawn) [0x0008d] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at Verse.AI.ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00000] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at Verse.AI.ThinkNode_PrioritySorter.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x000fc] in <6326ac03f61f45efb3178f3bfd084139>:0 
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by FxWolfxe** [comment]
this is fixed in the latest version, make sure you are using the most recent version of Humanoid Alien Races

**Comment by codeninja** [comment]
I have the same issue and have the up to date versions of both mods (via steam). I still have the same issue. Prisoner pawns converted and then recruited eat but do not refill the hunger bar.

**Comment by codeninja** [comment]
**MY CABBAGES**

**Comment by FxWolfxe** [comment]
can you post the log file for me to look at?

**Comment by codeninja** [comment]
here you go.
[Player-prev.log](https://github.com/Tachyonite/Pawnmorpher/files/5936349/Player-prev.log)

**Comment by codeninja** [comment]
Ok. So this seems to only impact enemy factions that convert to an animal while downed. When I recruit them while in animal form, they are unable to eat even after fully healed. If I use a reverter on them, they change back into their human form at the time of transformation, bleeding, missing limbs they had while animal, and now back to being hostile. 

This guy was a German Sheapard that almost starved to death before I could get reverters researched and crafted. When he changed back he's hostile, and nearly dead.

Maybe when they transform, the base pawn should be magically healed and made conscious ?
![image](https://user-images.githubusercontent.com/14914/107130484-78236980-6893-11eb-93e8-da853c425714.png)

**Comment by FxWolfxe** [comment]
looks like this is being caused by an interaction with VarietyMatters. I've already looked into this issue and it can't be fixed on our end

**Comment by codeninja** [comment]
Excellent. That mod's pissing me off anyway. YEET!
